### ISSUE TITLE
Missing NPM Token for Eclipse-zenoh-bot

### ISSUE THREAD

**Issue by Charles-Schleich** [eclipse-zenoh/.eclipsefdn#25]
The [Eclipse Zenoh NPM](https://www.npmjs.com/~eclipse-zenoh-bot) bot has a secret associated with it in order to publish to NPM: 
The secret has been created here https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5279#note_2857564
However I believe that it needs to be referenced in this repo in order to be accessible to the CI/CD workflows.

**Comment by netomi** [comment]
This is now resolved, the ORG_NPMJS_TOKEN is now available.
